// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models";

/**
 * Transfer represents a DCC file transfer
 */
export class Transfer {
    "id": string;
    "bot": string;
    "packNumber": number;
    "fileName": string;
    "fileSize": number;
    "downloaded": number;

    /**
     * bytes per second
     */
    "speed": number;
    "status": TransferStatus;
    "ip": string;
    "port": number;

    /**
     * For passive DCC
     */
    "token"?: string;
    "startTime": time$0.Time;
    "endTime"?: time$0.Time;
    "error"?: string;
    "savePath": string;
    "resumePos": number;

    /** Creates a new Transfer instance. */
    constructor($$source: Partial<Transfer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("bot" in $$source)) {
            this["bot"] = "";
        }
        if (!("packNumber" in $$source)) {
            this["packNumber"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = TransferStatus.$zero;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = null;
        }
        if (!("savePath" in $$source)) {
            this["savePath"] = "";
        }
        if (!("resumePos" in $$source)) {
            this["resumePos"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Transfer instance from a string or object.
     */
    static createFrom($$source: any = {}): Transfer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Transfer($$parsedSource as Partial<Transfer>);
    }
}

/**
 * TransferStatus represents the status of a transfer
 */
export enum TransferStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusConnecting = "connecting",
    StatusActive = "active",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
};
