// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as IRCService from "./ircservice";
import * as SettingsService from "./settingsservice";
import * as WalletService from "./walletservice";
import * as XDCCService from "./xdccservice";
export {
    IRCService,
    SettingsService,
    WalletService,
    XDCCService
};
