// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IRCService provides IRC functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as irc$0 from "../irc/models";

/**
 * AddServer adds a new IRC server
 */
export function AddServer(server: irc$0.Server | null): $CancellablePromise<void> {
    return $Call.ByID(1026151903, server);
}

/**
 * Connect connects to an IRC server
 * Connections are made asynchronously to allow multiple servers to connect concurrently
 */
export function Connect(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(40315921, serverID);
}

/**
 * Disconnect disconnects from an IRC server
 */
export function Disconnect(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(1942178755, serverID);
}

/**
 * GetChannelList returns the stored channel list for a server
 */
export function GetChannelList(serverID: string): $CancellablePromise<(irc$0.Channel | null)[]> {
    return $Call.ByID(95596778, serverID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetChannels returns joined channels for a server
 */
export function GetChannels(serverID: string): $CancellablePromise<(irc$0.Channel | null)[]> {
    return $Call.ByID(3143030007, serverID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetClient returns the IRC client for a server
 */
export function GetClient(serverID: string): $CancellablePromise<irc$0.Client | null> {
    return $Call.ByID(726009680, serverID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConnectionState returns the connection state for a server
 */
export function GetConnectionState(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(3901049368, serverID);
}

/**
 * GetLogs returns IRC protocol logs for a server
 */
export function GetLogs(serverID: string): $CancellablePromise<(irc$0.LogEntry | null)[]> {
    return $Call.ByID(1990417652, serverID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMessages returns messages for a specific channel
 */
export function GetMessages(serverID: string, channelName: string): $CancellablePromise<(irc$0.Message | null)[]> {
    return $Call.ByID(1676833335, serverID, channelName).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetServerTemplates returns available server templates/presets
 */
export function GetServerTemplates(): $CancellablePromise<irc$0.ServerTemplate[]> {
    return $Call.ByID(674556535).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetServers returns all configured servers
 */
export function GetServers(): $CancellablePromise<(irc$0.Server | null)[]> {
    return $Call.ByID(49470725).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * IsChannelListInProgress returns true if a channel list request is still in progress
 */
export function IsChannelListInProgress(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(109081460, serverID);
}

/**
 * JoinChannel joins a channel on a server
 */
export function JoinChannel(serverID: string, channel: string): $CancellablePromise<void> {
    return $Call.ByID(429650360, serverID, channel);
}

/**
 * ListChannels requests the channel list from a server
 */
export function ListChannels(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(917222425, serverID);
}

/**
 * PartChannel leaves a channel
 */
export function PartChannel(serverID: string, channel: string): $CancellablePromise<void> {
    return $Call.ByID(1863091695, serverID, channel);
}

/**
 * RemoveServer removes an IRC server
 */
export function RemoveServer(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(559452962, serverID);
}

/**
 * SendCTCP sends a CTCP command
 */
export function SendCTCP(serverID: string, target: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(2179970915, serverID, target, command);
}

/**
 * SendMessage sends a message to a channel or user
 */
export function SendMessage(serverID: string, target: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2437650166, serverID, target, message);
}

// Private type creation functions
const $$createType0 = irc$0.Channel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = irc$0.Client.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = irc$0.LogEntry.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = irc$0.Message.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = irc$0.ServerTemplate.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = irc$0.Server.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
