// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IRCService provides IRC functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as irc$0 from "../irc/models";

/**
 * AddServer adds a new IRC server
 */
export function AddServer(server: irc$0.Server | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1026151903, server) as any;
    return $resultPromise;
}

/**
 * Connect connects to an IRC server
 * Connections are made asynchronously to allow multiple servers to connect concurrently
 */
export function Connect(serverID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(40315921, serverID) as any;
    return $resultPromise;
}

/**
 * Disconnect disconnects from an IRC server
 */
export function Disconnect(serverID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1942178755, serverID) as any;
    return $resultPromise;
}

/**
 * GetChannelList returns the stored channel list for a server
 */
export function GetChannelList(serverID: string): Promise<(irc$0.Channel | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(95596778, serverID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetChannels returns joined channels for a server
 */
export function GetChannels(serverID: string): Promise<(irc$0.Channel | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3143030007, serverID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetClient returns the IRC client for a server
 */
export function GetClient(serverID: string): Promise<irc$0.Client | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(726009680, serverID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetConnectionState returns the connection state for a server
 */
export function GetConnectionState(serverID: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3901049368, serverID) as any;
    return $resultPromise;
}

/**
 * GetCurrentNick returns the current nickname for a server
 */
export function GetCurrentNick(serverID: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2984378159, serverID) as any;
    return $resultPromise;
}

/**
 * GetLogs returns IRC protocol logs for a server
 */
export function GetLogs(serverID: string): Promise<(irc$0.LogEntry | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1990417652, serverID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetMessages returns messages for a specific channel
 */
export function GetMessages(serverID: string, channelName: string): Promise<(irc$0.Message | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1676833335, serverID, channelName) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetServerTemplates returns available server templates/presets
 */
export function GetServerTemplates(): Promise<irc$0.ServerTemplate[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(674556535) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType12($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetServers returns all configured servers
 */
export function GetServers(): Promise<(irc$0.Server | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(49470725) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType15($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * IsChannelListInProgress returns true if a channel list request is still in progress
 */
export function IsChannelListInProgress(serverID: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(109081460, serverID) as any;
    return $resultPromise;
}

/**
 * JoinChannel joins a channel on a server
 */
export function JoinChannel(serverID: string, channel: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(429650360, serverID, channel) as any;
    return $resultPromise;
}

/**
 * ListChannels requests the channel list from a server
 */
export function ListChannels(serverID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(917222425, serverID) as any;
    return $resultPromise;
}

/**
 * PartChannel leaves a channel
 */
export function PartChannel(serverID: string, channel: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1863091695, serverID, channel) as any;
    return $resultPromise;
}

/**
 * RemoveServer removes an IRC server
 */
export function RemoveServer(serverID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(559452962, serverID) as any;
    return $resultPromise;
}

/**
 * SendCTCP sends a CTCP command
 */
export function SendCTCP(serverID: string, target: string, command: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2179970915, serverID, target, command) as any;
    return $resultPromise;
}

/**
 * SendMessage sends a message to a channel or user
 */
export function SendMessage(serverID: string, target: string, message: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2437650166, serverID, target, message) as any;
    return $resultPromise;
}

/**
 * SetApp sets the Wails application instance for event emission
 */
export function SetApp(app: application$0.App | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3267893326, app) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = irc$0.Channel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = irc$0.Client.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = irc$0.LogEntry.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = irc$0.Message.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = irc$0.ServerTemplate.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = irc$0.Server.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
