// @ts-nocheck
// Temporary placeholder bindings for SettingsService
// These will be regenerated by Wails CLI: wails3 generate bindings

import { $Call, $CancellablePromise } from '@wailsio/runtime';

export interface Settings {
  notifications: NotificationSettings;
  reconnect: ReconnectSettings;
  interface: InterfaceSettings;
  chat: ChatSettings;
  download: DownloadSettings;
  security: SecuritySettings;
}

export interface NotificationSettings {
  enabled: boolean;
  mentionsOnly: boolean;
  keywords: string[];
  sound: boolean;
  notifyWhenFocused: boolean;
}

export interface ReconnectSettings {
  enabled: boolean;
  maxAttempts: number;
  maxBackoff: number;
}

export interface InterfaceSettings {
  theme: string;
  fontSize: number;
  showTimestamps: boolean;
  show24HourTime: boolean;
  showUserList: boolean;
  showIRCLog: boolean;
  compactMode: boolean;
  animatedAvatars: boolean;
}

export interface ChatSettings {
  maxMessages: number;
  maxLogs: number;
  autoFocusInput: boolean;
  showJoinPart: boolean;
  showQuit: boolean;
  clickableURLs: boolean;
  inlineImages: boolean;
  emojiEnabled: boolean;
  commandHistory: number;
  defaultQuitMsg: string;
  defaultPartMsg: string;
}

export interface DownloadSettings {
  downloadPath: string;
  maxConcurrent: number;
  autoAccept: boolean;
  autoRetry: boolean;
  maxRetries: number;
  speedLimitKBps: number;
  notifyOnComplete: boolean;
  notifyOnFail: boolean;
}

export interface SecuritySettings {
  verifyCertificates: boolean;
  allowDCC: boolean;
  allowCTCP: boolean;
  ignoreList: string[];
}

export function GetSettings(): $CancellablePromise<Settings> {
    return $Call.ByID(9999999990); // Placeholder ID
}

export function SaveSettings(settings: Settings): $CancellablePromise<void> {
    return $Call.ByID(9999999991, settings); // Placeholder ID
}

export function ResetSettings(): $CancellablePromise<void> {
    return $Call.ByID(9999999992); // Placeholder ID
}
