// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides settings management functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models";

/**
 * ExportSettings exports settings as JSON string
 */
export function ExportSettings(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(892782203) as any;
    return $resultPromise;
}

/**
 * GetChatSettings returns chat settings
 */
export function GetChatSettings(): Promise<config$0.ChatSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(898476311) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDownloadSettings returns download settings
 */
export function GetDownloadSettings(): Promise<config$0.DownloadSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1543713697) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetInterfaceSettings returns interface settings
 */
export function GetInterfaceSettings(): Promise<config$0.InterfaceSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1901840314) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNotificationSettings returns notification settings
 */
export function GetNotificationSettings(): Promise<config$0.NotificationSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2287393270) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetReconnectSettings returns reconnect settings
 */
export function GetReconnectSettings(): Promise<config$0.ReconnectSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3998872564) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSecuritySettings returns security settings
 */
export function GetSecuritySettings(): Promise<config$0.SecuritySettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3035888023) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType11($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSettings returns the current settings
 */
export function GetSettings(): Promise<config$0.Settings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1254262105) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType13($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ImportSettings imports settings from JSON string
 */
export function ImportSettings(jsonData: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3558300504, jsonData) as any;
    return $resultPromise;
}

/**
 * ResetSettings resets settings to defaults
 */
export function ResetSettings(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3589330602) as any;
    return $resultPromise;
}

/**
 * SaveSettings saves the settings to disk
 */
export function SaveSettings(settings: config$0.Settings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(497773768, settings) as any;
    return $resultPromise;
}

/**
 * UpdateChatSettings updates chat settings
 */
export function UpdateChatSettings(settings: config$0.ChatSettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(613325482, settings) as any;
    return $resultPromise;
}

/**
 * UpdateDownloadSettings updates download settings
 */
export function UpdateDownloadSettings(settings: config$0.DownloadSettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2775200312, settings) as any;
    return $resultPromise;
}

/**
 * UpdateInterfaceSettings updates interface settings
 */
export function UpdateInterfaceSettings(settings: config$0.InterfaceSettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2137196777, settings) as any;
    return $resultPromise;
}

/**
 * UpdateNotificationSettings updates notification settings
 */
export function UpdateNotificationSettings(settings: config$0.NotificationSettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2112182791, settings) as any;
    return $resultPromise;
}

/**
 * UpdateReconnectSettings updates reconnect settings
 */
export function UpdateReconnectSettings(settings: config$0.ReconnectSettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(421016391, settings) as any;
    return $resultPromise;
}

/**
 * UpdateSecuritySettings updates security settings
 */
export function UpdateSecuritySettings(settings: config$0.SecuritySettings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2657131786, settings) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = config$0.ChatSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.DownloadSettings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.InterfaceSettings.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = config$0.NotificationSettings.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = config$0.ReconnectSettings.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = config$0.SecuritySettings.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = config$0.Settings.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
