// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WalletService handles cryptocurrency wallet operations
 * This service is exposed to the frontend via Wails bindings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wallet$0 from "../wallet/models";

/**
 * CreateWallet initializes a new wallet with the given password
 */
export function CreateWallet(password: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2018212653, password) as any;
    return $resultPromise;
}

/**
 * GetAllBalances returns balances for all coins
 */
export function GetAllBalances(): Promise<(wallet$0.Balance | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1974710094) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetBalance returns the balance for a specific coin
 */
export function GetBalance(coin: string): Promise<wallet$0.Balance | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1659729484, coin) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDepositAddress returns the deposit address for a coin
 */
export function GetDepositAddress(coin: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(98541478, coin) as any;
    return $resultPromise;
}

/**
 * GetStatus returns the wallet status
 */
export function GetStatus(): Promise<wallet$0.WalletStatus | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3917951802) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSupportedCoins returns the list of supported cryptocurrencies
 */
export function GetSupportedCoins(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3472831212) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTransactions returns transaction history for a coin
 */
export function GetTransactions(coin: string, limit: number): Promise<(wallet$0.Transaction | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1677436937, coin, limit) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType8($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Initialize sets up the wallet service with configuration
 */
export function Initialize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1718783682) as any;
    return $resultPromise;
}

/**
 * IsEnabled returns whether wallet features are enabled
 */
export function IsEnabled(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2673240517) as any;
    return $resultPromise;
}

/**
 * IsInitialized returns whether any wallet has been set up
 */
export function IsInitialized(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3086222922) as any;
    return $resultPromise;
}

/**
 * IsUnlocked returns whether the wallet is unlocked
 */
export function IsUnlocked(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3554650753) as any;
    return $resultPromise;
}

/**
 * Lock locks the wallet
 */
export function Lock(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2238324515) as any;
    return $resultPromise;
}

/**
 * ProcessCommand handles wallet IRC commands
 * Returns a CommandResult that can be displayed in the chat
 */
export function ProcessCommand(command: string, args: string[]): Promise<wallet$0.CommandResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(703108366, command, args) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Send sends cryptocurrency to an address
 */
export function Send(coin: string, toAddress: string, amount: string, memo: string): Promise<wallet$0.Transaction | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3721764882, coin, toAddress, amount, memo) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Unlock unlocks the wallet with the given password
 */
export function Unlock(password: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1795452744, password) as any;
    return $resultPromise;
}

/**
 * ValidateAddress validates an address for a coin
 */
export function ValidateAddress(coin: string, address: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2325676738, coin, address) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = wallet$0.Balance.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = wallet$0.WalletStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = wallet$0.Transaction.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = wallet$0.CommandResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
