// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * XDCCService provides XDCC functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dcc$0 from "../dcc/models";

/**
 * CancelDownload cancels and removes a download
 */
export function CancelDownload(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3338022325, transferID);
}

/**
 * GetDownloads returns all downloads
 */
export function GetDownloads(): $CancellablePromise<(dcc$0.Transfer | null)[]> {
    return $Call.ByID(3532902546).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ParseDCCSend parses a DCC SEND message and starts the download
 * This would typically be called when receiving a CTCP DCC SEND message
 */
export function ParseDCCSend(serverID: string, bot: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2865191870, serverID, bot, message);
}

/**
 * PauseDownload pauses a download
 */
export function PauseDownload(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3127134715, transferID);
}

/**
 * RequestPack requests an XDCC pack from a bot
 */
export function RequestPack(serverID: string, bot: string, packNumber: number): $CancellablePromise<void> {
    return $Call.ByID(1111509985, serverID, bot, packNumber);
}

/**
 * ResumeDownload resumes a download
 */
export function ResumeDownload(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(2573614140, transferID);
}

/**
 * SetMaxConcurrentDownloads sets the maximum number of concurrent downloads
 */
export function SetMaxConcurrentDownloads(max: number): $CancellablePromise<void> {
    return $Call.ByID(1029505585, max);
}

// Private type creation functions
const $$createType0 = dcc$0.Transfer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
