// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models";

/**
 * Channel represents an IRC channel
 */
export class Channel {
    "name": string;
    "topic": string;
    "users": number;

    /**
     * List of nicknames in the channel
     */
    "userList": string[];
    "joined": boolean;
    "messages": (Message | null)[];

    /** Creates a new Channel instance. */
    constructor($$source: Partial<Channel> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("users" in $$source)) {
            this["users"] = 0;
        }
        if (!("userList" in $$source)) {
            this["userList"] = [];
        }
        if (!("joined" in $$source)) {
            this["joined"] = false;
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     */
    static createFrom($$source: any = {}): Channel {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userList" in $$parsedSource) {
            $$parsedSource["userList"] = $$createField3_0($$parsedSource["userList"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField5_0($$parsedSource["messages"]);
        }
        return new Channel($$parsedSource as Partial<Channel>);
    }
}

/**
 * Client represents an IRC client connection
 */
export class Client {
    "Server": Server | null;
    "State": ConnectionState;

    /**
     * Joined channels (Joined=true)
     */
    "Channels": { [_: string]: Channel | null };

    /**
     * All channels from LIST command (Joined=false)
     */
    "ChannelList": (Channel | null)[];
    "Logs": (LogEntry | null)[];

    /**
     * Event callbacks for real-time updates
     */
    "OnMessageReceived": any;
    "OnLogAdded": any;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("Server" in $$source)) {
            this["Server"] = null;
        }
        if (!("State" in $$source)) {
            this["State"] = (0 as ConnectionState);
        }
        if (!("Channels" in $$source)) {
            this["Channels"] = {};
        }
        if (!("ChannelList" in $$source)) {
            this["ChannelList"] = [];
        }
        if (!("Logs" in $$source)) {
            this["Logs"] = [];
        }
        if (!("OnMessageReceived" in $$source)) {
            this["OnMessageReceived"] = null;
        }
        if (!("OnLogAdded" in $$source)) {
            this["OnLogAdded"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        const $$createField0_0 = $$createType5;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Server" in $$parsedSource) {
            $$parsedSource["Server"] = $$createField0_0($$parsedSource["Server"]);
        }
        if ("Channels" in $$parsedSource) {
            $$parsedSource["Channels"] = $$createField2_0($$parsedSource["Channels"]);
        }
        if ("ChannelList" in $$parsedSource) {
            $$parsedSource["ChannelList"] = $$createField3_0($$parsedSource["ChannelList"]);
        }
        if ("Logs" in $$parsedSource) {
            $$parsedSource["Logs"] = $$createField4_0($$parsedSource["Logs"]);
        }
        return new Client($$parsedSource as Partial<Client>);
    }
}

/**
 * ConnectionState represents the state of an IRC connection
 */
export enum ConnectionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Disconnected = 0,
    Connecting = 1,
    Connected = 2,
    Registered = 3,
};

/**
 * LogEntry represents an IRC protocol log entry
 */
export class LogEntry {
    "timestamp": time$0.Time;

    /**
     * "in" or "out"
     */
    "direction": string;
    "raw": string;

    /**
     * "info", "error", "protocol"
     */
    "type": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * Message represents an IRC message
 */
export class Message {
    "timestamp": time$0.Time;
    "from": string;
    "to": string;
    "text": string;

    /**
     * message, notice, action, join, part, quit
     */
    "type": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * Server represents an IRC server configuration
 */
export class Server {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "ssl": boolean;
    "nick": string;
    "user": string;
    "realName": string;
    "password"?: string;

    /**
     * Enable automatic reconnection on disconnect
     */
    "autoReconnect": boolean;

    /**
     * Password for NickServ authentication
     */
    "nickServPassword"?: string;

    /** Creates a new Server instance. */
    constructor($$source: Partial<Server> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("ssl" in $$source)) {
            this["ssl"] = false;
        }
        if (!("nick" in $$source)) {
            this["nick"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("realName" in $$source)) {
            this["realName"] = "";
        }
        if (!("autoReconnect" in $$source)) {
            this["autoReconnect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     */
    static createFrom($$source: any = {}): Server {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server($$parsedSource as Partial<Server>);
    }
}

/**
 * ServerTemplate represents a pre-configured server template
 */
export class ServerTemplate {
    "name": string;
    "host": string;
    "port": number;
    "ssl": boolean;
    "description": string;

    /** Creates a new ServerTemplate instance. */
    constructor($$source: Partial<ServerTemplate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("ssl" in $$source)) {
            this["ssl"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerTemplate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerTemplate($$parsedSource as Partial<ServerTemplate>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Message.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Server.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Channel.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Array($$createType7);
const $$createType10 = LogEntry.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
