// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models";

/**
 * Balance represents a wallet balance
 */
export class Balance {
    "coin": Coin;

    /**
     * Decimal string for display (e.g., "0.00123456")
     */
    "amount": string;

    /**
     * Smallest unit (satoshis for BSV, lamports for SOL)
     */
    "amountSmall": number;

    /**
     * Confirmed balance in smallest unit
     */
    "confirmed": number;

    /**
     * Unconfirmed/pending balance
     */
    "unconfirmed": number;

    /**
     * Current price in USD (0 if unavailable)
     */
    "priceUsd": number;

    /**
     * Total value in USD
     */
    "valueUsd": number;
    "updatedAt": time$0.Time;

    /** Creates a new Balance instance. */
    constructor($$source: Partial<Balance> = {}) {
        if (!("coin" in $$source)) {
            this["coin"] = ("" as Coin);
        }
        if (!("amount" in $$source)) {
            this["amount"] = "";
        }
        if (!("amountSmall" in $$source)) {
            this["amountSmall"] = 0;
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = 0;
        }
        if (!("unconfirmed" in $$source)) {
            this["unconfirmed"] = 0;
        }
        if (!("priceUsd" in $$source)) {
            this["priceUsd"] = 0;
        }
        if (!("valueUsd" in $$source)) {
            this["valueUsd"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Balance instance from a string or object.
     */
    static createFrom($$source: any = {}): Balance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Balance($$parsedSource as Partial<Balance>);
    }
}

/**
 * Coin represents a supported cryptocurrency
 */
export enum Coin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CoinBSV = "bsv",
    CoinSolana = "sol",
};

/**
 * CommandResult represents the result of a wallet command
 */
export class CommandResult {
    "success": boolean;
    "message": string;
    "data"?: any;
    "error"?: string;

    /** Creates a new CommandResult instance. */
    constructor($$source: Partial<CommandResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult($$parsedSource as Partial<CommandResult>);
    }
}

/**
 * Transaction represents a wallet transaction
 */
export class Transaction {
    "id": string;
    "coin": Coin;
    "type": TxType;

    /**
     * Decimal string
     */
    "amount": string;

    /**
     * Smallest unit
     */
    "amountSmall": number;

    /**
     * Fee in decimal
     */
    "fee": string;

    /**
     * Fee in smallest unit
     */
    "feeSmall": number;

    /**
     * To/From address
     */
    "address": string;

    /**
     * Blockchain transaction hash
     */
    "txHash": string;
    "status": TxStatus;
    "confirmations": number;

    /**
     * Optional memo/note
     */
    "memo": string;

    /**
     * IRC nick if applicable
     */
    "recipient": string;
    "timestamp": time$0.Time;

    /** Creates a new Transaction instance. */
    constructor($$source: Partial<Transaction> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("coin" in $$source)) {
            this["coin"] = ("" as Coin);
        }
        if (!("type" in $$source)) {
            this["type"] = ("" as TxType);
        }
        if (!("amount" in $$source)) {
            this["amount"] = "";
        }
        if (!("amountSmall" in $$source)) {
            this["amountSmall"] = 0;
        }
        if (!("fee" in $$source)) {
            this["fee"] = "";
        }
        if (!("feeSmall" in $$source)) {
            this["feeSmall"] = 0;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ("" as TxStatus);
        }
        if (!("confirmations" in $$source)) {
            this["confirmations"] = 0;
        }
        if (!("memo" in $$source)) {
            this["memo"] = "";
        }
        if (!("recipient" in $$source)) {
            this["recipient"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Transaction instance from a string or object.
     */
    static createFrom($$source: any = {}): Transaction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Transaction($$parsedSource as Partial<Transaction>);
    }
}

/**
 * TxStatus represents the status of a transaction
 */
export enum TxStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TxStatusPending = "pending",
    TxStatusConfirmed = "confirmed",
    TxStatusFailed = "failed",
};

/**
 * TxType represents the type of transaction
 */
export enum TxType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TxTypeSend = "send",
    TxTypeReceive = "receive",
    TxTypeTipSent = "tip_sent",
    TxTypeTipReceived = "tip_received",
};

/**
 * WalletStatus represents the overall wallet status
 */
export class WalletStatus {
    /**
     * Has wallet been created
     */
    "initialized": boolean;

    /**
     * Is wallet currently unlocked
     */
    "unlocked": boolean;

    /**
     * Supported coins
     */
    "coins": Coin[];

    /**
     * For auto-lock
     */
    "lastActive": time$0.Time;

    /** Creates a new WalletStatus instance. */
    constructor($$source: Partial<WalletStatus> = {}) {
        if (!("initialized" in $$source)) {
            this["initialized"] = false;
        }
        if (!("unlocked" in $$source)) {
            this["unlocked"] = false;
        }
        if (!("coins" in $$source)) {
            this["coins"] = [];
        }
        if (!("lastActive" in $$source)) {
            this["lastActive"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletStatus {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coins" in $$parsedSource) {
            $$parsedSource["coins"] = $$createField2_0($$parsedSource["coins"]);
        }
        return new WalletStatus($$parsedSource as Partial<WalletStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
