// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ChatSettings configures chat behavior
 */
export class ChatSettings {
    /**
     * Max messages to store per channel (default: 500)
     */
    "maxMessages": number;

    /**
     * Max log entries to store (default: 200)
     */
    "maxLogs": number;

    /**
     * Auto-focus input after sending
     */
    "autoFocusInput": boolean;

    /**
     * Show JOIN/PART messages
     */
    "showJoinPart": boolean;

    /**
     * Show QUIT messages
     */
    "showQuit": boolean;

    /**
     * Make URLs clickable
     */
    "clickableURLs": boolean;

    /**
     * Show inline image previews
     */
    "inlineImages": boolean;

    /**
     * Enable emoji rendering
     */
    "emojiEnabled": boolean;

    /**
     * Command history size (default: 50)
     */
    "commandHistory": number;

    /**
     * Default quit message
     */
    "defaultQuitMsg": string;

    /**
     * Default part message
     */
    "defaultPartMsg": string;

    /** Creates a new ChatSettings instance. */
    constructor($$source: Partial<ChatSettings> = {}) {
        if (!("maxMessages" in $$source)) {
            this["maxMessages"] = 0;
        }
        if (!("maxLogs" in $$source)) {
            this["maxLogs"] = 0;
        }
        if (!("autoFocusInput" in $$source)) {
            this["autoFocusInput"] = false;
        }
        if (!("showJoinPart" in $$source)) {
            this["showJoinPart"] = false;
        }
        if (!("showQuit" in $$source)) {
            this["showQuit"] = false;
        }
        if (!("clickableURLs" in $$source)) {
            this["clickableURLs"] = false;
        }
        if (!("inlineImages" in $$source)) {
            this["inlineImages"] = false;
        }
        if (!("emojiEnabled" in $$source)) {
            this["emojiEnabled"] = false;
        }
        if (!("commandHistory" in $$source)) {
            this["commandHistory"] = 0;
        }
        if (!("defaultQuitMsg" in $$source)) {
            this["defaultQuitMsg"] = "";
        }
        if (!("defaultPartMsg" in $$source)) {
            this["defaultPartMsg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSettings($$parsedSource as Partial<ChatSettings>);
    }
}

/**
 * DownloadSettings configures XDCC download behavior
 */
export class DownloadSettings {
    /**
     * Default download directory
     */
    "downloadPath": string;

    /**
     * Max concurrent downloads (default: 3)
     */
    "maxConcurrent": number;

    /**
     * Auto-accept downloads
     */
    "autoAccept": boolean;

    /**
     * Auto-retry failed downloads
     */
    "autoRetry": boolean;

    /**
     * Max retry attempts (default: 3)
     */
    "maxRetries": number;

    /**
     * Download speed limit in KB/s (0 = unlimited)
     */
    "speedLimitKBps": number;

    /**
     * Notify when download completes
     */
    "notifyOnComplete": boolean;

    /**
     * Notify when download fails
     */
    "notifyOnFail": boolean;

    /** Creates a new DownloadSettings instance. */
    constructor($$source: Partial<DownloadSettings> = {}) {
        if (!("downloadPath" in $$source)) {
            this["downloadPath"] = "";
        }
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("autoAccept" in $$source)) {
            this["autoAccept"] = false;
        }
        if (!("autoRetry" in $$source)) {
            this["autoRetry"] = false;
        }
        if (!("maxRetries" in $$source)) {
            this["maxRetries"] = 0;
        }
        if (!("speedLimitKBps" in $$source)) {
            this["speedLimitKBps"] = 0;
        }
        if (!("notifyOnComplete" in $$source)) {
            this["notifyOnComplete"] = false;
        }
        if (!("notifyOnFail" in $$source)) {
            this["notifyOnFail"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadSettings($$parsedSource as Partial<DownloadSettings>);
    }
}

/**
 * InterfaceSettings configures UI behavior
 */
export class InterfaceSettings {
    /**
     * Theme name (default, dark, light)
     */
    "theme": string;

    /**
     * Font size in pixels (default: 11)
     */
    "fontSize": number;

    /**
     * Show message timestamps
     */
    "showTimestamps": boolean;

    /**
     * Use 24-hour time format
     */
    "show24HourTime": boolean;

    /**
     * Show user list sidebar
     */
    "showUserList": boolean;

    /**
     * Show IRC protocol log
     */
    "showIRCLog": boolean;

    /**
     * Use compact message layout
     */
    "compactMode": boolean;

    /**
     * Animate user avatars (if any)
     */
    "animatedAvatars": boolean;

    /** Creates a new InterfaceSettings instance. */
    constructor($$source: Partial<InterfaceSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("showTimestamps" in $$source)) {
            this["showTimestamps"] = false;
        }
        if (!("show24HourTime" in $$source)) {
            this["show24HourTime"] = false;
        }
        if (!("showUserList" in $$source)) {
            this["showUserList"] = false;
        }
        if (!("showIRCLog" in $$source)) {
            this["showIRCLog"] = false;
        }
        if (!("compactMode" in $$source)) {
            this["compactMode"] = false;
        }
        if (!("animatedAvatars" in $$source)) {
            this["animatedAvatars"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): InterfaceSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterfaceSettings($$parsedSource as Partial<InterfaceSettings>);
    }
}

/**
 * NotificationSettings configures desktop notification behavior
 */
export class NotificationSettings {
    /**
     * Master toggle for notifications
     */
    "enabled": boolean;

    /**
     * Only notify for mentions and PMs
     */
    "mentionsOnly": boolean;

    /**
     * Custom highlight keywords
     */
    "keywords": string[];

    /**
     * Play sound on notification
     */
    "sound": boolean;

    /**
     * Show notifications when window focused
     */
    "notifyWhenFocused": boolean;

    /** Creates a new NotificationSettings instance. */
    constructor($$source: Partial<NotificationSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("mentionsOnly" in $$source)) {
            this["mentionsOnly"] = false;
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = [];
        }
        if (!("sound" in $$source)) {
            this["sound"] = false;
        }
        if (!("notifyWhenFocused" in $$source)) {
            this["notifyWhenFocused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationSettings {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField2_0($$parsedSource["keywords"]);
        }
        return new NotificationSettings($$parsedSource as Partial<NotificationSettings>);
    }
}

/**
 * ReconnectSettings configures auto-reconnect behavior
 */
export class ReconnectSettings {
    /**
     * Enable auto-reconnect globally
     */
    "enabled": boolean;

    /**
     * Maximum reconnect attempts (default: 10)
     */
    "maxAttempts": number;

    /**
     * Maximum backoff in seconds (default: 60)
     */
    "maxBackoff": number;

    /** Creates a new ReconnectSettings instance. */
    constructor($$source: Partial<ReconnectSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("maxAttempts" in $$source)) {
            this["maxAttempts"] = 0;
        }
        if (!("maxBackoff" in $$source)) {
            this["maxBackoff"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReconnectSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectSettings($$parsedSource as Partial<ReconnectSettings>);
    }
}

/**
 * SecuritySettings configures security behavior
 */
export class SecuritySettings {
    /**
     * Verify SSL certificates (default: false for IRC)
     */
    "verifyCertificates": boolean;

    /**
     * Allow DCC connections
     */
    "allowDCC": boolean;

    /**
     * Allow CTCP requests
     */
    "allowCTCP": boolean;

    /**
     * List of ignored nicknames/hosts
     */
    "ignoreList": string[];

    /** Creates a new SecuritySettings instance. */
    constructor($$source: Partial<SecuritySettings> = {}) {
        if (!("verifyCertificates" in $$source)) {
            this["verifyCertificates"] = false;
        }
        if (!("allowDCC" in $$source)) {
            this["allowDCC"] = false;
        }
        if (!("allowCTCP" in $$source)) {
            this["allowCTCP"] = false;
        }
        if (!("ignoreList" in $$source)) {
            this["ignoreList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecuritySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SecuritySettings {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignoreList" in $$parsedSource) {
            $$parsedSource["ignoreList"] = $$createField3_0($$parsedSource["ignoreList"]);
        }
        return new SecuritySettings($$parsedSource as Partial<SecuritySettings>);
    }
}

/**
 * Settings represents all application settings
 */
export class Settings {
    "notifications": NotificationSettings;
    "reconnect": ReconnectSettings;
    "interface": InterfaceSettings;
    "chat": ChatSettings;
    "download": DownloadSettings;
    "security": SecuritySettings;
    "wallet": WalletSettings;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("notifications" in $$source)) {
            this["notifications"] = (new NotificationSettings());
        }
        if (!("reconnect" in $$source)) {
            this["reconnect"] = (new ReconnectSettings());
        }
        if (!("interface" in $$source)) {
            this["interface"] = (new InterfaceSettings());
        }
        if (!("chat" in $$source)) {
            this["chat"] = (new ChatSettings());
        }
        if (!("download" in $$source)) {
            this["download"] = (new DownloadSettings());
        }
        if (!("security" in $$source)) {
            this["security"] = (new SecuritySettings());
        }
        if (!("wallet" in $$source)) {
            this["wallet"] = (new WalletSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField0_0($$parsedSource["notifications"]);
        }
        if ("reconnect" in $$parsedSource) {
            $$parsedSource["reconnect"] = $$createField1_0($$parsedSource["reconnect"]);
        }
        if ("interface" in $$parsedSource) {
            $$parsedSource["interface"] = $$createField2_0($$parsedSource["interface"]);
        }
        if ("chat" in $$parsedSource) {
            $$parsedSource["chat"] = $$createField3_0($$parsedSource["chat"]);
        }
        if ("download" in $$parsedSource) {
            $$parsedSource["download"] = $$createField4_0($$parsedSource["download"]);
        }
        if ("security" in $$parsedSource) {
            $$parsedSource["security"] = $$createField5_0($$parsedSource["security"]);
        }
        if ("wallet" in $$parsedSource) {
            $$parsedSource["wallet"] = $$createField6_0($$parsedSource["wallet"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * WalletSettings configures cryptocurrency wallet behavior
 */
export class WalletSettings {
    /**
     * Enable wallet features
     */
    "enabled": boolean;

    /**
     * Default coin for commands (bsv, sol)
     */
    "defaultCoin": string;

    /**
     * Auto-lock wallet after N minutes of inactivity
     */
    "autoLockMins": number;

    /**
     * Show USD price alongside crypto amounts
     */
    "showPriceUsd": boolean;

    /**
     * BSV Settings
     * "mainnet" or "testnet"
     */
    "bsvNetwork": string;

    /**
     * ARC API endpoint
     */
    "arcUrl": string;

    /**
     * ARC API key (stored encrypted)
     */
    "arcApiKey": string;

    /**
     * WhatsOnChain API endpoint
     */
    "wocUrl": string;

    /**
     * Solana Settings
     * "mainnet-beta" or "devnet"
     */
    "solanaNetwork": string;

    /**
     * Custom RPC URL (optional)
     */
    "solanaRpcUrl": string;

    /**
     * Transaction Limits
     * Max tip amount in BSV (e.g., "0.01")
     */
    "maxTipBsv": string;

    /**
     * Max tip amount in SOL (e.g., "1.0")
     */
    "maxTipSol": string;

    /**
     * Daily limit in BSV (e.g., "0.1")
     */
    "dailyLimitBsv": string;

    /**
     * Daily limit in SOL (e.g., "10.0")
     */
    "dailyLimitSol": string;

    /** Creates a new WalletSettings instance. */
    constructor($$source: Partial<WalletSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("defaultCoin" in $$source)) {
            this["defaultCoin"] = "";
        }
        if (!("autoLockMins" in $$source)) {
            this["autoLockMins"] = 0;
        }
        if (!("showPriceUsd" in $$source)) {
            this["showPriceUsd"] = false;
        }
        if (!("bsvNetwork" in $$source)) {
            this["bsvNetwork"] = "";
        }
        if (!("arcUrl" in $$source)) {
            this["arcUrl"] = "";
        }
        if (!("arcApiKey" in $$source)) {
            this["arcApiKey"] = "";
        }
        if (!("wocUrl" in $$source)) {
            this["wocUrl"] = "";
        }
        if (!("solanaNetwork" in $$source)) {
            this["solanaNetwork"] = "";
        }
        if (!("solanaRpcUrl" in $$source)) {
            this["solanaRpcUrl"] = "";
        }
        if (!("maxTipBsv" in $$source)) {
            this["maxTipBsv"] = "";
        }
        if (!("maxTipSol" in $$source)) {
            this["maxTipSol"] = "";
        }
        if (!("dailyLimitBsv" in $$source)) {
            this["dailyLimitBsv"] = "";
        }
        if (!("dailyLimitSol" in $$source)) {
            this["dailyLimitSol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WalletSettings($$parsedSource as Partial<WalletSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = NotificationSettings.createFrom;
const $$createType2 = ReconnectSettings.createFrom;
const $$createType3 = InterfaceSettings.createFrom;
const $$createType4 = ChatSettings.createFrom;
const $$createType5 = DownloadSettings.createFrom;
const $$createType6 = SecuritySettings.createFrom;
const $$createType7 = WalletSettings.createFrom;
